import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Sidepanel } from "@/components";
const inter = Inter({ subsets: ["latin"] });
const sansation = localFont({
  src: "../fonts/Sansation_Regular.ttf",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sansation.className}>
        <Sidepanel />
        <div className="bg-accent-green w-full h-full rounded-lg overflow-auto p-3 ml-2 flex flex-col">
          {children}
        </div>
      </body>
    </html>
  );
}
